language: ruby

rvm:
  - 2.2
  - 2.3.5 # https://github.com/travis-ci/travis-ci/issues/5361
  - 2.4.2
gemfile:
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.0.gemfile
before_install:
  - gem update bundler

script: "bundle exec rake test"
